% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Budget \& Hochrechnung - Analyse Report},
  pdfauthor={PoC System},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Budget \& Hochrechnung - Analyse Report}
\author{PoC System}
\date{2026-02-21}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}

\subsection{Executive Summary}\label{executive-summary}

Dieser Report vergleicht die aktuelle Berechnung mit einer Basis-Version
(bu\_v001.csv).

\textbf{Basis-Version:} bu\_v001.csv\\
\textbf{Aktuelle Version:} bu\_v004.csv\\
\textbf{Generiert:} 21.02.2026 14:55:38

\subsubsection{Gesamtübersicht}\label{gesamtuxfcbersicht}

Die folgende Tabelle zeigt die wichtigsten KPIs im Vergleich:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1053}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1447}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1711}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1316}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1447}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1711}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1316}}@{}}
\caption{KPI Vergleich: Basis vs.~Aktuell}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Produkt
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
SQ (Basis)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
SQ (Aktuell)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
SQ Diff \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
CR (Basis)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
CR (Aktuell)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
CR Diff \%
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Produkt
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
SQ (Basis)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
SQ (Aktuell)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
SQ Diff \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
CR (Basis)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
CR (Aktuell)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
CR Diff \%
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Amb\_T & 0.4259 & 0.4647 & 9.0977 & 0.5512 & 0.6005 & 8.9570 \\
Amb\_S & 0.4847 & 0.6041 & 24.6220 & 0.5658 & 0.7549 & 33.4256 \\
Amb\_C & 0.5619 & 0.2278 & -59.4618 & 0.6974 & 0.3343 & -52.0620 \\
Hosp\_P & 0.3282 & 0.3919 & 19.4313 & 0.4207 & 0.4947 & 17.5889 \\
Hosp\_HP & 0.4541 & 0.9971 & 119.5943 & 0.5742 & 1.1074 & 92.8433 \\
\end{longtable}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Detaillierte Pro-Produkt
Analyse}\label{detaillierte-pro-produkt-analyse}

\subsubsection{Produkt: Amb\_T}\label{produkt-amb_t}

\paragraph{Kennzahlen}\label{kennzahlen}

\begin{longtable}[]{@{}lrr@{}}
\caption{KPIs für Amb\_T}\tabularnewline
\toprule\noalign{}
Metrik & Basis & Aktuell \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Metrik & Basis & Aktuell \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Schadenquote (SQ) & 0.4259 & 0.4647 \\
Combined Ratio (CR) & 0.5512 & 0.6005 \\
Bestand & 96221.0000 & 201567.0000 \\
NVP & 280.8200 & 283.8100 \\
Verdiente Prämie & 275.2200 & 275.9100 \\
\end{longtable}

\paragraph{Bewertung}\label{bewertung}

\begin{itemize}
\tightlist
\item
  ⚠️ Schadenquote um 9.1\% gestiegen- ⚠️ Combined Ratio um 9\% gestiegen
  \#\#\# Produkt: Amb\_S \#\#\#\# Kennzahlen
\end{itemize}

\begin{longtable}[]{@{}lrr@{}}
\caption{KPIs für Amb\_S}\tabularnewline
\toprule\noalign{}
Metrik & Basis & Aktuell \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Metrik & Basis & Aktuell \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Schadenquote (SQ) & 0.4847 & 6.0410e-01 \\
Combined Ratio (CR) & 0.5658 & 7.5490e-01 \\
Bestand & 225594.0000 & 2.8441e+05 \\
NVP & 159.3700 & 2.7919e+02 \\
Verdiente Prämie & 155.2700 & 2.6969e+02 \\
\end{longtable}

\paragraph{Bewertung}\label{bewertung-1}

\begin{itemize}
\tightlist
\item
  ⚠️ Schadenquote um 24.6\% gestiegen- ⚠️ Combined Ratio um 33.4\%
  gestiegen \#\#\# Produkt: Amb\_C \#\#\#\# Kennzahlen
\end{itemize}

\begin{longtable}[]{@{}lrr@{}}
\caption{KPIs für Amb\_C}\tabularnewline
\toprule\noalign{}
Metrik & Basis & Aktuell \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Metrik & Basis & Aktuell \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Schadenquote (SQ) & 0.5619 & 0.2278 \\
Combined Ratio (CR) & 0.6974 & 0.3343 \\
Bestand & 193332.0000 & 116088.0000 \\
NVP & 262.8200 & 254.0100 \\
Verdiente Prämie & 255.7200 & 248.9100 \\
\end{longtable}

\paragraph{Bewertung}\label{bewertung-2}

\begin{itemize}
\tightlist
\item
  ✅ Schadenquote um 59.5\% verbessert- ✅ Combined Ratio um 52.1\%
  verbessert \#\#\# Produkt: Hosp\_P \#\#\#\# Kennzahlen
\end{itemize}

\begin{longtable}[]{@{}lrr@{}}
\caption{KPIs für Hosp\_P}\tabularnewline
\toprule\noalign{}
Metrik & Basis & Aktuell \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Metrik & Basis & Aktuell \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Schadenquote (SQ) & 0.3282 & 0.3919 \\
Combined Ratio (CR) & 0.4207 & 0.4947 \\
Bestand & 92013.0000 & 145023.0000 \\
NVP & 211.5000 & 216.5500 \\
Verdiente Prämie & 208.4000 & 212.1500 \\
\end{longtable}

\paragraph{Bewertung}\label{bewertung-3}

\begin{itemize}
\tightlist
\item
  ⚠️ Schadenquote um 19.4\% gestiegen- ⚠️ Combined Ratio um 17.6\%
  gestiegen \#\#\# Produkt: Hosp\_HP \#\#\#\# Kennzahlen
\end{itemize}

\begin{longtable}[]{@{}lrr@{}}
\caption{KPIs für Hosp\_HP}\tabularnewline
\toprule\noalign{}
Metrik & Basis & Aktuell \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Metrik & Basis & Aktuell \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Schadenquote (SQ) & 4.5410e-01 & 0.9971 \\
Combined Ratio (CR) & 5.7420e-01 & 1.1074 \\
Bestand & 2.8596e+05 & 251871.0000 \\
NVP & 2.1960e+02 & 149.3700 \\
Verdiente Prämie & 2.1220e+02 & 145.0700 \\
\end{longtable}

\paragraph{Bewertung}\label{bewertung-4}

\begin{itemize}
\tightlist
\item
  ⚠️ Schadenquote um 119.6\% gestiegen- ⚠️ Combined Ratio um 92.8\%
  gestiegen
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Grafische Übersicht}\label{grafische-uxfcbersicht}

\pandocbounded{\includegraphics[keepaspectratio]{report_files/figure-pdf/plot-changes-1.png}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Fazit}\label{fazit}

Dieser Report dokumentiert die Unterschiede zwischen der Basis-Version
und der aktuellen Berechnung. Die detaillierte Pro-Produkt Analyse
ermöglicht eine fundierte Bewertung der Veränderungen.

\textbf{Report generiert automatisch von der Budget \& Hochrechnung PoC
Anwendung}




\end{document}
